CREATE DATABASE DEVELSYSTEMS;

CREATE TABLE USUARIO (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Username VARCHAR(50) NOT NULL,
	Passwd VARCHAR(200) NOT NULL
);

CREATE TABLE ENCUESTA (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Usuario INT NOT NULL,
	Nombre VARCHAR(100) NOT NULL,
	Descripcion VARCHAR(300) NOT NULL,
	FOREIGN KEY (Usuario) REFERENCES USUARIO(Id) ON DELETE CASCADE
);

CREATE TABLE TIPO (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE CAMPO (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Encuesta INT NOT NULL,
	Titulo VARCHAR(100) NOT NULL,
	Requerido BIT NOT NULL,
	Tipo INT NOT NULL,
	FOREIGN KEY (Encuesta) REFERENCES ENCUESTA(Id) ON DELETE CASCADE,
	FOREIGN KEY (Tipo) REFERENCES TIPO(Id) ON DELETE CASCADE
);

CREATE TABLE RESPUESTA (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Fecha DATETIME NOT NULL
);

CREATE TABLE RESPUESTA_CAMPO (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Campo INT NOT NULL,
	Informacion VARCHAR(500) NOT NULL,
	FOREIGN KEY (Campo) REFERENCES CAMPO(Id) ON DELETE CASCADE
);

INSERT INTO TIPO (Nombre)
VALUES
	('text'), ('date'), ('number')
;

GO
CREATE PROCEDURE CREAR_USUARIO (
	@pUsuario VARCHAR(50),
	@pPasswd VARCHAR(200)
)
AS
BEGIN
	INSERT INTO USUARIO (
		Username,
		Passwd
	) 
	VALUES(
		@pUsuario,
		@pPasswd
	)
END

GO
CREATE PROCEDURE LOGUEAR_USUARIO (
	@pUsuario VARCHAR(50),
	@pPasswd VARCHAR(200)
)
AS
BEGIN
	SELECT 
		Id,
		Username
	FROM USUARIO
	WHERE
		Username = @pUsuario
		AND Passwd = @pPasswd
END

GO
CREATE PROCEDURE OBTENER_ENCUESTAS (
	@pUsuario INT
)
AS
BEGIN
	SELECT 
		Id,
		Nombre,
		Descripcion
	FROM ENCUESTA
	WHERE Usuario = @pUsuario
END